obj-$(CONFIG_TOUCHSCREEN_SEC_TS)   += sec_touch.o
sec_touch-objs   += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_cmd.o \
	sec_ts_only_vendor.o

EXTRA_CFLAGS += -I$(srctree)/$(src)/../../display -I$(srctree)/$(src)/../common -I$(srctree)/$(src)/../common/include
