#define CONFIG_DRM_SAMSUNG_DECON 1
#define CONFIG_DRM_SAMSUNG_DPP 1
#define CONFIG_DRM_SAMSUNG_DSI 1
#define CONFIG_DRM_SAMSUNG_WB 1
#define CONFIG_DRM_SAMSUNG_TUI 1

#define CONFIG_MALI_MIDGARD 1
#define CONFIG_MALI_GATOR_SUPPORT 1
#define CONFIG_MALI_REAL_HW 1
#define CONFIG_MALI_MIDGARD_DVFS 1
#define CONFIG_MALI_EXPERT 1
#define CONFIG_MALI_PIXEL_GPU_QOS 1
#define CONFIG_MALI_PIXEL_GPU_BTS 1
#define CONFIG_MALI_PIXEL_GPU_THERMAL 1
#define CONFIG_MALI_PIXEL_GPU_SECURE_RENDERING 1

#define CONFIG_GOOGLE_BMS_MODULE 1
#define CONFIG_GOOGLE_BATTERY_MODULE 1
#define CONFIG_GOOGLE_CHARGER_MODULE 1
#define CONFIG_GOOGLE_CPM_MODULE 1
#define CONFIG_GOOGLE_BEE_MODULE 1
#define CONFIG_GOOGLE_DUAL_BATT_GAUGE_MODULE 1
#define CONFIG_USB_OVERHEAT_MITIGATION_MODULE 1
#define CONFIG_PMIC_MAX77729_MODULE 1
#define CONFIG_UIC_MAX77729_MODULE 1
#define CONFIG_CHARGER_MAX77729_MODULE 1
#define CONFIG_CHARGER_MAX77759_MODULE 1
#define CONFIG_MAXQ_MAX77759_MODULE 1
#define CONFIG_CHARGER_P9221_MODULE 1
#define CONFIG_MAX1720X_BATTERY_MODULE 1
#define CONFIG_MAX_M5_MODULE 1
#define CONFIG_PCA9468_MODULE 1
#define CONFIG_MAX20339_MODULE 1

#define CONFIG_TOUCHSCREEN_TBN 1
#define CONFIG_TOUCHSCREEN_HEATMAP 1
#define CONFIG_TOUCHSCREEN_OFFLOAD 1
