include $(srctree)/drivers/google-modules/google-modules.conf

LINUXINCLUDE += -include $(srctree)/drivers/google-modules/google-modules-conf.h

obj-y += display/samsung/
obj-y += wlan/bcmdhd/bcm4389/
obj-y += gpu/mali_pixel/
obj-y += gpu/mali_kbase/
obj-y += lwis/
obj-y += edgetpu/drivers/edgetpu/
obj-y += bms/
obj-y += amplifiers/drv2624/
obj-y += amplifiers/cs40l25/
obj-y += amplifiers/cs35l41/
obj-y += amplifiers/audiometrics/
obj-y += aoc/
obj-y += aoc/alsa/
obj-y += aoc/usb/
obj-y += touch/common/
obj-y += touch/fts_touch/ftm5/
obj-y += touch/sec_touch/
obj-y += power/reset/
obj-y += bluetooth/broadcom/
obj-y += nfc/
obj-y += uwb/kernel/
